# Generated by Django 6.0.7 on 2026-09-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_matrix_offload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='corpus_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
